@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiYTA1MjhjLWQ4MGQtNGI3Yi05YzRkLTBhMWE4YWY3MDRmNyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzIyNzM1MywiZXhwIjoxNzE3NTcyOTUzfQ.EnnmDWZ1HFaRrkTz2wY-caapYpcAbd4gyRnXqnRZP5c

//login
###
POST http://localhost:5003/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Admin1234!"
}

//create patient
###
POST http://localhost:5003/patient
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullname": "Bagus",
    "place_birth": "Banyumas",
    "date_birth": "2024-05-26",
    "gender": "L",
    "address": "sokaraja",
    "work": "programer",
    "phone": "08123456789",
    "history_illness": "not-found",
    "nik": "1234567890123456", 
    "namaIbuKandung": "Sumantry",
    "agama": "Islam",
    "alamatKTP": "sokaraja",
    "kecamatan": "sokaraja",
    "kelurahan": "sokaraja",
    "kota": "Banyumas",
    "kodePos": "53181",
    "rt": "3",
    "rw": "1"
}

//GET PATIENT
###
GET http://localhost:5003/patient?search=12345
Authorization: Bearer {{token}}
Content-Type: application/json

//GET PATIENT DETAIL
###
GET http://localhost:5003/patient/d3574dc7-6f3d-4851-ac92-72ab120d2f29
Authorization: Bearer {{token}}
Content-Type: application/json

//UPDATE PATIENT
###
PUT http://localhost:5003/patient/d3574dc7-6f3d-4851-ac92-72ab120d2f29
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullname": "bagus",
    "place_birth": "bagus",
    "date_birth": "2023-02-13",
    "gender": "L",
    "address": "Banyumas",
    "work": "student",
    "phone": "01236470789",
    "history_illness": "not-found",
    "nik": "1234567890123471", 
    "namaIbuKandung": "Sumantry",
    "agama": "Islam",
    "alamatKTP": "sokaraja",
    "kecamatan": "sokaraja",
    "kelurahan": "sokaraja",
    "kota": "Banyumas",
    "kodePos": "53181",
    "rt": "3",
    "rw": "1"
}

//CREATE REKAM MEDIS
###
POST http://localhost:5003/rekam-medis
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "date": "2024-05-26",
    "diagnosis": "kepala pusing",
    "therapy": "kurangi melihat cahaya",
    "service": [{"name":"cabut gigi","price":"300000"},{"name":"Tambal Gigi","price":"500000"},{"name":"Pasang Behel","price":"400000"}],
    "description": "istirahat yang cukup",
    "odontogram": [
        {
          "oke": "masuk",
          "sip": "ya"
        },
        {
          "oke": "masuk",
          "sip": "ya"
        }
      ],
    "patient_id": "274ff275-0988-4713-a9a6-608215929b16"
}

//GET ALL REKAM MEDIS
###
GET http://localhost:5003/rekam-medis?page=&search=1234567890123471&sorting=&startDate=2024-02-19&endDate=2024-05-30
Authorization: Bearer {{token}}
Content-Type: application/json

//GET DETAIL REKAM MEDIS
###
GET http://localhost:5003/rekam-medis/0435846a-cbf1-4bc8-8c86-95c7dab2c19e
Authorization: Bearer {{token}}
Content-Type: application/json

//Koreksi Rekam Medis
###
PUT http://localhost:5003/rekam-medis-koreksi/0435846a-cbf1-4bc8-8c86-95c7dab2c19e
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "koreksi": "string"
}

//GET Invoice
###
GET http://localhost:5003/invoice?page=&search=1234567890123471&sorting=&invoiceId=&startDate=2024-05-26&endDate=2024-05-26&patientId=
Authorization: Bearer {{token}}
Content-Type: application/json

//Dashboard
###
GET http://localhost:5003/dashboard
Authorization: Bearer {{token}}
Content-Type: application/json


//CREATE Obat
###
POST http://localhost:5003/obat
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "code": "BDRX",
    "name": "Bodrex",
    "price": "10000"
}

//GET ALL OBAT
###
GET http://localhost:5003/obat?page=&search=&sorting=
Authorization: Bearer {{token}}
Content-Type: application/json

//Update Obat
###
PUT http://localhost:5003/obat/6374e03d-3f06-427e-b442-3b23432a82e6
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Bodrex C",
    "price": "15000",
    "code": "BDRX X"
}

//GET DETAIL OBAT
###
GET http://localhost:5003/obat/6374e03d-3f06-427e-b442-3b23432a82e6
Authorization: Bearer {{token}}
Content-Type: application/json